[package]
name = "wasmer/ghostty-web"
version = "0.4.24"
description = "The wasmer.sh website"
entrypoint = "start"

[dependencies]
"wasmer/static-web-server" = "^1"

[fs]
"/public" = "dist"
"/etc/static-web-server" = "etc"

[[command]]
name = "start"
module = "wasmer/static-web-server:webserver"
runner = "wasi"

[command.annotations.wasi]
env = ["SERVER_CONFIG_FILE=/etc/static-web-server/config.toml"]
